### ISSUE TITLE
Has the new stake manager contract been deployed?

### ISSUE THREAD

**Issue by petejkim** [maticnetwork/Polygon-Improvement-Proposals#345]
Has the new stake manager contract been deployed? If so, could you update PIP-42 to show the new address?

**Comment by hrook1** [comment]
Hey, these details have just been added to PIP-42, https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-42.md. 

@simonDos is the author and will be able to provide more details if needed.

**Comment by petejkim** [comment]
Thank you.

@simonDos PIP-42 still says "address to be determined" in the first paragraph, update that as well, please.

Has the timelock schedule transaction been executed already? If so, could you share the transaction hash please?

**Comment by hrook1** [comment]
@petejkim Tx hash: 0x95feca752c03fe3e4036de9667f1d9f90d67d2f47175f243025e31409bdb9866.

Details have also been updated in the PIP.

**Comment by hrook1** [comment]
@petejkim Tx hash: 0x95feca752c03fe3e4036de9667f1d9f90d67d2f47175f243025e31409bdb9866.

Details have also been updated in the PIP.

**Comment by petejkim** [comment]
@hrook1 That's the transaction that deploys the new implementation. I was looking for the transaction to schedule the actual upgrade from the timelock contract. I guess you aren't going to be using a timelock for this upgrade?

**Comment by petejkim** [comment]
Hi @hrook1 @simonDos,

It took a while to figure things out and I am not sure if I covered all the necessary steps due to documentation being rather sparse, but I was able to write a script that simulates the upgrade, and could verify that it works. 

One thing I wasn't so sure about was whether you'll be upgrading the emission manager (step 1 in the following script) by 1. having the existing emission manager proxy to point at the new emission manager contract OR 2. replacing them by revoking and granting the EMISSION_ROLE in the POL token contract. Any idea?

Once the upgrade is scheduled in the Timelock, would you be able to let me know so I can also help independently verify? Thanks!

```bash
# requires a forked mainnet running locally
POL_TOKEN_CONTRACT="0x455e53CBB86018Ac2B8092FdCd39d8444aFFC3F6"
POL_MIGRATION_CONTRACT="0x29e7DF7b6A1B2b07b731457f499E1696c60E2C4e"
MATIC_TOKEN_CONTRACT="0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0"

EMISSION_PROXY_ADMIN="0xEBea33f2c92D03556b417F4F572B2FbbE62C39c3"
GOVERNANCE_PROXY="0x6e7a5820baD6cebA8Ef5ea69c0C92EbbDAc9CE48"
TIMELOCK_CONTRACT="0xCaf0aa768A3AE1297DF20072419Db8Bb8b5C8cEf"

for addr in "$EMISSION_PROXY_ADMIN" "$GOVERNANCE_PROXY" "$TIMELOCK_CONTRACT"
do
    cast rpc anvil_impersonateAccount $addr
    cast rpc anvil_setBalance $addr 1000000000000000000
done

# validator share proxy contract for validator 72
VALIDATOR_SHARE_PROXY="0x40EA81066321dA24af02F87E05Ded5B85E79e437"

echo "1. upgrade emission manager...."
EMISSION_MANAGER_PROXY="0xbC9f74b3b14f460a6c47dCdDFd17411cBc7b6c53"
NEW_EMISSION_MANAGER_CONTRACT="0xbC9f74b3b14f460a6c47dCdDFd17411cBc7b6c53"

cast send $EMISSION_MANAGER_PROXY "upgradeTo(address)" $NEW_EMISSION_MANAGER_CONTRACT -f $EMISSION_PROXY_ADMIN --unlocked --gas-limit 1000000
cast call $EMISSION_MANAGER_PROXY "implementation()(address)" -f $EMISSION_PROXY_ADMIN

echo "2. upgrade validator share in the registry..."
REGISTRY_CONTRACT="0x33a02E6cC863D393d6Bf231B697b82F6e499cA71"
NEW_VALIDATOR_SHARE_CONTRACT="0x053fa9b934b83e1e0ffc7e98a41aadc3640bb462"

cast send $REGISTRY_CONTRACT "updateContractMap(bytes32,address)" `cast keccak validatorShare` $NEW_VALIDATOR_SHARE_CONTRACT -f $GOVERNANCE_PROXY --unlocked --gas-limit 1000000
cast call $VALIDATOR_SHARE_PROXY "implementation()(address)"

echo "3. set pol address in the registry..."
cast send $REGISTRY_CONTRACT "updateContractMap(bytes32,address)" `cast keccak pol` $POL_TOKEN_CONTRACT -f $GOVERNANCE_PROXY --unlocked --gas-limit 1000000
cast call $REGISTRY_CONTRACT "contractMap(bytes32)(address)" `cast keccak pol`

echo "matic and pol balances of stake manager before upgrade: "
cast call $MATIC_TOKEN_CONTRACT 'balanceOf(address)(uint256)' $STAKE_MANAGER_PROXY
cast call $POL_TOKEN_CONTRACT 'balanceOf(address)(uint256)' $STAKE_MANAGER_PROXY

echo "4. upgrade stake manager..."
STAKE_MANAGER_PROXY="0x5e3Ef299fDDf15eAa0432E6e66473ace8c13D908"
NEW_STAKE_MANAGER_CONTRACT="0x97a3500083348A147F419b8a65717909762c389f"

cast send $STAKE_MANAGER_PROXY "updateImplementation(address)" $NEW_STAKE_MANAGER_CONTRACT -f $TIMELOCK_CONTRACT --unlocked --gas-limit 1000000

echo "5. initialize POL on stake manager..."
cast send $STAKE_MANAGER_PROXY "initializePOL(address,address)" $POL_TOKEN_CONTRACT $POL_MIGRATION_CONTRACT -f $GOVERNANCE_PROXY --unlocked --gas-limit 1000000

echo "matic and pol balances of stake manager after upgrade: "
cast call $MATIC_TOKEN_CONTRACT 'balanceOf(address)(uint256)' $STAKE_MANAGER_PROXY
cast call $POL_TOKEN_CONTRACT 'balanceOf(address)(uint256)' $STAKE_MANAGER_PROXY
```
